<?php if ($block->getConfig()[0]) { ?>
    <div class="left-float-ads">
        <a href="<?php echo $block->getConfig()[3] ?>"><img src="<?php echo $block->getConfig()[2] ?>"></a>
    </div>
<?php } ?>

<?php if ($block->getConfig()[4]) { ?>
    <div class="right-float-ads">
        <a href="<?php echo $block->getConfig()[7] ?>"><img src="<?php echo $block->getConfig()[6] ?>"></a>
    </div>
<?php } ?>
